<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class User_model extends CI_Model {
    public function __construct() {
        parent::__construct();
        $this->load->database();
    }

    // Ensure the USERS table exists and is initialized
    public function ensure_users_table() {
        // Step 1: Check if the USERS table exists
        if (!$this->table_exists('USERS')) {
            // Step 2: Create the USERS table
            $this->create_users_table();
        }

        // Step 3: Check if the USERS table has data
        if ($this->is_table_empty('USERS')) {
            // Step 4: Insert default admin user
            $this->insert_admin_user();
        }
    }

    // Check if a table exists in the database
    private function table_exists($table_name) {
        $query = $this->db->query("
            SELECT 1 
            FROM RDB\$RELATIONS 
            WHERE RDB\$RELATION_NAME = ?
        ", [strtoupper($table_name)]);
        return $query->num_rows() > 0;
    }
    

    // Create the USERS table
    private function create_users_table() {
        $query = "
            CREATE TABLE USERS (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                GOOGLE_ID VARCHAR(255) UNIQUE, -- For Google Login
                USERNAME VARCHAR(255) NOT NULL, -- For manual login
                PASSWORD VARCHAR(255) NOT NULL, -- For manual login
                EMAIL VARCHAR(255) UNIQUE, -- Email address (both manual and Google)
                IS_DEFAULT BOOLEAN DEFAULT FALSE, -- Flag for default admin or system accounts
                CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- Timestamp for account creation
            )
        ";
        $this->db->query($query);
    }
    

    // Check if a table is empty
    private function is_table_empty($table_name) {
        $query = $this->db->get($table_name);
        return $query->num_rows() === 0;
    }

    // Insert default admin user
    private function insert_admin_user() {
        $hashed_password = password_hash('admin', PASSWORD_DEFAULT);
        
        // First default user with username and password
        $this->db->insert('USERS', [
            'USERNAME' => 'admin',
            'PASSWORD' => $hashed_password,
            'EMAIL' => null // No email for this user
        ]);

        // Second default user with email and password
        $this->db->insert('USERS', [
            'USERNAME' => 'Nadicom Technology Centre', // No username for this user
            'EMAIL' => 'nadicomsql@gmail.com',
            'PASSWORD' => $hashed_password
        ]);
    }
    
    // Validate user credentials
    public function validate_user($username, $password) {
        $this->db->where("USERNAME", $username);
        $query = $this->db->get("USERS");
    
        if ($query->num_rows() === 1) {
            $user = $query->row();
    
            // Use password_verify to compare the input password with the hashed password
            if (password_verify($password, $user->PASSWORD)) {
                return $user;
            }
        }
    
        return false;
    }

    public function email_exists($email) {
        $this->db->where('EMAIL', $email);
        $query = $this->db->get('USERS');
        return $query->num_rows() > 0;
    }

    public function reset_password($username, $password) {
        // Hash the new password
        $hashed_password = password_hash($password, PASSWORD_DEFAULT);
    
        // Update the user's password
        $this->db->where('USERNAME', $username);
        return $this->db->update('USERS', ['PASSWORD' => $hashed_password]);
    }
    
    
    public function create_user($data) {
        // Check if the username or email already exists
        $this->db->where('USERNAME', $data['USERNAME']);
        $this->db->or_where('EMAIL', $data['EMAIL']);
        $query = $this->db->get('USERS');
    
        if ($query->num_rows() > 0) {
            // User already exists
            return false;
        }
    
        // Insert the new user into the database
        return $this->db->insert('USERS', $data);
    }    
    

    public function find_or_create_user($googleId, $email, $name) {
        // Check if user exists
        $this->db->where('GOOGLE_ID', $googleId);
        $query = $this->db->get('USERS');
    
        if ($query->num_rows() > 0) {
            return $query->row(); // Return existing user
        } else {
            // Create new user
            $data = [
                'GOOGLE_ID' => $googleId,
                'EMAIL' => $email,
                'USERNAME' => $name,
                'PASSWORD' => password_hash('admin', PASSWORD_DEFAULT), // Placeholder password
                'CREATED_AT' => date('Y-m-d H:i:s')
            ];
            $this->db->insert('USERS', $data);
            $data['id'] = $this->db->insert_id();
            return (object) $data;
        }
    }    
}
